<?php

namespace Muni\Arq\ArqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalleRepository extends EntityRepository
{
}
